### ISSUE TITLE
Observables only updated if "activated" first

### ISSUE THREAD

**Issue by cstjean** [sglyon/PlotlyWebIO.jl#7]
I don't know if that's intentional, but in a notebook, if I execute

```julia
using PlotlyWebIO
sc = PlotlyWebIO.scatter(x=[1,2], y=[2,3])
wpl = PlotlyWebIO.WebIOPlot(sc)
wpl
```

then select a point, then display `wpl["selected"]`, I get an empty dict (observable). If I then select another point, the dict gets updated correctly. It seems that `wpl["selected"]` isn't updated unless it's "active". Am I supposed to only rely on `WebIO.on`?

**Comment by cstjean** [comment]
cc. @shashi

**Comment by shashi** [comment]
> Am I supposed to only rely on WebIO.on?

WebIO will (intentionally) send stuff to Julia only if there is a `on` handler on the observable to avoid excess communication. You can also set up a no-op handler if you want the values.
